<?php
return array(
	//'键'=>值,	
	'DB_PREFIX'=>'',
	'DB_HOST'=>'',
	'DB_NAME'=>'',
	'DB_USER'=>'',
	'DB_PW'=>'',
	'DB_PORT'=>'',
	'DB_USEPREFIX'=>true,
	//'URL_SEPE'=>'-',
	'URL_SUFFIX'=>'.html',
	'URL_MODE'=>1,//0=>一般PATHINFO,1=>REWRITE+PATHINFO
	'APP_URL'=>'http://localhost/',
	//'TPL_SEPE'=>'-';
	//'DEFAULT_METHOD'=>'index/test',
	'GZIP'=>true,
	'LANG'=>'zh_cn',
	);
?>
